---
title: "zonal_stat"
author: "Lallu Nikerthil Prathapan"
date: "2/27/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages("D:/EAGLE/Master_Thesis_Hannes/1/R/packages/exactextractr_0.10.0.tar.gz", repos = NULL, type = "source")
```


```{r}
# List of packages to install
#packages_to_install <- c("exactextracter")

# Install the packages
#install.packages(packages_to_install)
```


```{r}
library(sf)
library(ggplot2)
library(raster)
library(exactextractr)
library(terra)
library(dplyr)
library(gridExtra)
```


#Zonal statistics for each of the global EO population datasets

#Loading the data of camps

```{r}
url <- "data_camps/idp_camps_224.shp"
sf_data <- st_read(url) 
```
# 1. GHSL DATA
```{r}
ghsl_raster_path<-"D:/EAGLE/Master_Thesis_Hannes/1/ghsl_pop_2020_mollweid_100m/merged_ghsl.tif"
# Read the raster file into R
ghsl_raster <- raster(ghsl_raster_path)

```

```{r}
# Display information about the raster
print(ghsl_raster)
```
```{r}
# Plot the raster
plot(ghsl_raster)
```
```{r}
# function

# weighted sum per polygon (using the size of the pixel covered by the polygon "coverage_fraction")

extract_sum  <-  function(raster, polygon, field){

  polygon $id_tmp <- as.data.frame(polygon)[,field]

  v.exact <- exactextractr::exact_extract(raster, polygon, include_cols = 'id_tmp', max_cells_in_memory=3e+10)

  x <- do.call("rbind",v.exact)

  x[,"ras_name"] <- x[, "value"] * x$coverage_fraction

  x_sum <- x %>%

    dplyr::group_by(id_tmp)%>%

    dplyr::summarise_at("ras_name", sum, na.rm = TRUE)

polygon <- polygon %>%

    left_join(x_sum, by = "id_tmp")

  rm(x,v.exact,x_sum)

  return(polygon)

}
```


```{r}
# Data
sf_data <- st_read(url) 
polygon_camps <-sf_data

```


```{r}
raster_population <- rast('D:/EAGLE/Master_Thesis_Hannes/1/ghsl_pop_2020_mollweid_100m/merged_ghsl.tif')
```

```{r}
# Call function

polygon_camps <- extract_sum(raster_population, polygon_camps,"Name")

```


#Difference in the population
```{r}
# Assuming you have a column named "N_INDVID" in the polygon_camps data frame
# Adjust the column name if needed

# Subtract N_INDVID from ras_name
polygon_camps$ghsl_difference <- polygon_camps$N_INDVID - polygon_camps$ras_name

# View the resulting data frame with the new "difference" column
print(polygon_camps)

```
#Writing the output of the ghsl extract

```{r}

library(sf)

# Convert the data frame to an sf object
sf_polygon_camps <- st_as_sf(polygon_camps)

# Remove Z (3D) coordinates
sf_polygon_camps <- st_zm(sf_polygon_camps, drop = TRUE)

# Export the sf object to a shapefile
st_write(sf_polygon_camps,
 "ghsl_output/polygon_camps_justghsl.shp")

```


```{r}
library(ggplot2)

# Assuming you have a column named "ras_name" in the polygon_camps data frame
# Change the column name if you used a different name in the code

# Define the ggplot object
ggplot(polygon_camps, aes(fill = ras_name)) +
  geom_sf() +  # Plot the polygons
  scale_fill_viridis_c() +  # Choose a color scale (you can change to your preference)
  labs(title = "Zonal Statistics of GHSL Values for Camps") +
  theme_minimal()

```
```{r}
# Scatter plot with site_status
ggplot(polygon_camps, aes(x = ras_name, y = N_INDVID, color = Site_Statu)) +
  geom_point() +
  labs(title = "Comparison between estimated and survey iom populations",
       x = "Estimated population",
       y = "Iom surveyed population") +
  theme_minimal()
```
```{r}
# Scatter plot with different colors based on Shelt_type
ggplot(polygon_camps, aes(x = ras_name, y = N_INDVID, color = Shelt_type)) +
  geom_point() +
  labs(title = "Comparison between ras_name and N_INDVID",
       x = "ras_name",
       y = "N_INDVID") +
  theme_minimal()
```

```{r}
# Scatter plot comparing N_INDIVID and N_HH
plot1 <- ggplot(polygon_camps, aes(x = N_INDVID, y = N_HH, color = ras_name)) +
  geom_point() +
  labs(title = "Comparison between N_INDVID and N_HH",
       x = "N_INDVID",
       y = "N_HH") +
  theme_minimal()

# Scatter plot comparing N_INDIVID and ras_name
plot2 <- ggplot(polygon_camps, aes(x = N_INDVID, y = ras_name, color = ras_name)) +
  geom_point() +
  labs(title = "Comparison between N_INDVID and ras_name",
       x = "N_INDVID",
       y = "ras_name") +
  theme_minimal()

# Scatter plot comparing N_HH and ras_name
plot3 <- ggplot(polygon_camps, aes(x = N_HH, y = ras_name, color = ras_name)) +
  geom_point() +
  labs(title = "Comparison between N_HH and ras_name",
       x = "N_HH",
       y = "ras_name") +
  theme_minimal()

# Arrange the plots in a grid
grid.arrange(plot1, plot2, plot3, ncol = 2)
```

#World POP

```{r}
World_pop <- rast('D:/EAGLE/Master_Thesis_Hannes/1/world_pop/nga_ppp_2020.tif')
```

```{r}
# Read the raster file into R
world_pop_raster <- rast(World_pop)
# Display information about the raster
print(world_pop_raster)
```
```{r}
# Check the extent of the raster
# Check the extent of the raster
extent_worldpop <- terra::ext(world_pop_raster)
print(extent_worldpop)

# Check summary information about the polygons
summary(polygon_camps)

# Create a SpatialPolygons object from the extent
extent_poly <- SpatialPolygons(
  list(
    Polygons(
      list(
        Polygon(
          cbind(
            c(extent_worldpop[1], extent_worldpop[1], extent_worldpop[2], extent_worldpop[2], extent_worldpop[1]),
            c(extent_worldpop[3], extent_worldpop[4], extent_worldpop[4], extent_worldpop[3], extent_worldpop[3])
          )
        )
      ),
      ID = "1"
    )
  )
)

# Check if the polygons overlap with the raster extent
overlap <- over(polygon_camps, extent_poly)
print(overlap)

```



```{r}
# Get values from the raster
raster_values <- raster::getValues(world_pop_raster)

# Print the values
print(raster_values)
```

```{r}

# Call function

polygon_camps <- extract_sum(world_pop_raster, polygon_camps,"Name")

```


